name: Continuous Deployment

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            arch: [amd64, arm64]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Build Docker image
            run: |
              docker build --platform linux/${{ matrix.arch }} -t protodesk .

          - name: Run Docker image
            run: |
              docker run --rm -v $(pwd)/dist:/app/dist --name protodesk-container protodesk

          - name: Create a versioned archive of the build
            run: |
              cd dist && tar -czf protodesk-${{ github.event.release.tag_name }}_${{ matrix.arch }}.tar.gz app/

          - name: Upload release asset
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ github.event.release.upload_url}}
              asset_path: dist/protodesk-${{ github.event.release.tag_name }}_${{ matrix.arch }}.tar.gz
              asset_name: protodesk-${{ github.event.release.tag_name }}_${{ matrix.arch }}.tar.gz
              asset_content_type: application/gzip
