name: Continuous Integration

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up python
            uses: actions/setup-python@v4
            with:
              python-version: '3.12'
        
          - name: Install dependencies
            run: |
                pip3 install flake8

          - name: Run flake8
            run: |
              flake8 .

    multiarch-build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          arch: [amd64, arm64]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build Docker image
          run: |
            docker build --platform linux/${{ matrix.arch }} -t protodesk .
